server:
  port: 9111
  servlet:
    context-path: /user/

spring:
  application:
    name: user-server
  profiles:
    active:
      - druid
      - dev

logging:
  config: classpath:log4j2.xml
  level:
    com.baomidou.example.mapper: debug