server:
  port: 9111
  servlet:
    context-path: /user/

spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weixin?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

logging:
  level:
    com.baomidou.example.mapper: debug