server:
  port: 9111
  servlet:
    context-path: /user/

spring:
  application:
    name: user-server
  profiles:
    active:
      - druid
      - dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  config: classpath:log4j2.xml
  level:
    com.baomidou.example.mapper: debug
