server:
  port: 9111
  servlet:
    context-path: /user/

spring:
  application:
    name: user-server
  profiles:
    active:
      - druid
      - dev

logging:
  config: classpath:log4j2.xml
  level:
    com.baomidou.example.mapper: debug

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
